### ISSUE TITLE
Support for object storage in different namespace then MLFlow and SSL

### ISSUE THREAD

**Issue by Barteus** [canonical/mlflow-operator#77]
This s3_url will work only if object storage and mlflow are in the same namespace.
https://github.com/canonical/mlflow-operator/blob/6d7b891bb3af07c460489b59803c07cd853af82f/charms/mlflow-server/src/services/s3.py#L71

Additionally, we have a field "secure" in object storage relation, but when creating the URL we hardcode the HTTP:
https://github.com/canonical/mlflow-operator/blob/6d7b891bb3af07c460489b59803c07cd853af82f/charms/mlflow-server/src/charm.py#L345
https://github.com/canonical/mlflow-operator/blob/6d7b891bb3af07c460489b59803c07cd853af82f/charms/mlflow-server/src/charm.py#L360

**Comment by ca-scribner** [comment]
This line:
https://github.com/canonical/mlflow-operator/blob/6d7b891bb3af07c460489b59803c07cd853af82f/charms/mlflow-server/src/services/s3.py#L71

I think is ok, but the when instantiating that wrapper here:
https://github.com/canonical/mlflow-operator/blob/0a3733c7934042563e3c45d27ece4ebe6c6e7109/charms/mlflow-server/src/charm.py#L301

we should be using the fully qualified name (eg: `service-name.namespace`) rather than just the service name.

**Comment by i-chvets** [comment]
I agree with @ca-scribner on the solution.

**Comment by i-chvets** [comment]
Adding to be fixed.
Low priority.

**Comment by i-chvets** [comment]
Fix is merged.
